[project]
name = "ultralytics-yolo11-export-rknn"
version = "0.1.0"
description = "ultralytics export rknn, support YOLOv8, YOLO11 and YOLO26."
readme = "README.md"
requires-python = "==3.12.3"
dependencies = [
    "rknn-toolkit2==2.3.2",
    "ultralytics==8.3.9+rknn",
    "setuptools==66.1.1",
    "click>=8.3.1",
    "onnx==1.18.0",
    "onnxruntime==1.18.0",
    "onnxslim>=0.1.82",
]

[project.scripts]
ultralytics-yolo11-export-rknn-cli = "ultralytics_yolo11_export_rknn.cli:main"


[build-system]
requires = ["uv_build>=0.7.4,<0.8.0"]
build-backend = "uv_build"

[tool.uv.sources]
ultralytics = { path = "wheels/ultralytics-8.3.9+rknn-py3-none-any.whl" }
rknn-toolkit2 = { path = "wheels/rknn_toolkit2-2.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" }
